### ISSUE TITLE
Plugin does not read from /var/go/.github

### ISSUE THREAD

**Issue by stevendgonzales** [srinivasupadhya/gocd-build-status-notifier#1]
The plugin loads github credentials from system properties, and works fine, but it does not work if credentials are put in /var/go/.github as described in README.  The code does appears to only pull form system properties: https://github.com/srinivasupadhya/gocd-build-status-notifier/blob/master/src/main/java/com/tw/go/plugin/provider/github/GitHubProvider.java#L24-27

**Comment by srinivasupadhya** [comment]
when system property isn't provided [this](https://github.com/srinivasupadhya/gocd-build-status-notifier/blob/master/src/main/java/com/tw/go/plugin/provider/github/GitHubProvider.java#L56) happens. And since we use [github-api](https://github.com/srinivasupadhya/gocd-build-status-notifier/blob/master/pom.xml#L39) library it picks `~/.github` for credentials.

**Comment by stevendgonzales** [comment]
I will give it another try.  It didn't seem to be working for me but based on the code above it looks like it would work.  

Thanks for the plugin by the way, this was a big feature that was missing and I think it will go a long way.

**Comment by srinivasupadhya** [comment]
> I think it will go a long way.

:) hoping for the same :+1:

**Comment by stevendgonzales** [comment]
So when I set values in system properties, i am able to update PR status in our Enterprise Github.

However, GitHub.connect() does not appear to be honoring the values i set in /var/go/.github as the endpoint being logged in `plugin-github.pr.status.log` is not my custom endpoint, but the default `api.github.com`.  What is even more odd is that /var/go/.github is being read just fine by the gocd-build-github-pull-requests plugin.

**Comment by srinivasupadhya** [comment]
i made small changes to docs. in `~/.github` you will need to populate:
```
login=johndoe
oauth=thisaintatoken
```
I have it setup for build.go.cd so it should work.

**Comment by stevendgonzales** [comment]
i have been trying to with login/password, but like i said above, it is not reading the /var/go/.github file is not being read.  The  as `https://api.github.com` is the endpoint that is logged in the request instead of the enterprise endpoint I have set.  However, the `gocd-build-github-pull-requests` plugin is reading this file successfully and building PRs.

**Comment by stevendgonzales** [comment]
I am using the last release published here, I am going to try building a fresh .jar

**Comment by stevendgonzales** [comment]
I am also not getting an [IOException](https://github.com/kohsuke/github-api/blob/master/src/main/java/org/kohsuke/github/GitHubBuilder.java#l66) which i would expect if the file could not be read

**Comment by stevendgonzales** [comment]
I think i found the solution.  For reading from ~./github to work with a custom Enterprise Github endpoint, the feature from [this pull request](https://github.com/kohsuke/github-api/pull/156/files) is required!  The POM for this build uses github-api-1.61 which does not yet include this feature.  I will build a new version of this plugin with github-api-1.68 and test

**Comment by stevendgonzales** [comment]
tested with new build and custom endpoint now works
